description: Application Generator
fields:
  - id: name
    type: input
    default: Otto
    label: Enter name

  - id: lastName
    type: input
    default: Giron
    label: Enter last name

  - id: projectManagers 
    type: map
    label: Enter project leads
    fields:
      - id: infrastructure
        type: input
        label: Infrastructure

      - id: platform
        type: input
        label: Platform

      - id: tooling
        type: input
        label: Infrastructure
        default: Javier Alvarez

  - id: projects
    type: list
    label: Enter the list of projects
    size: 5
    field:
        type: input
        label: Project Name
