
version: 1.0
#template name
name: hello-world
#Fields to be requested to the user for this template
fields:
  - id: name
    type: input
    default: "Otto"
    label: "Enter name"

  - id: lastName
    type: input
    default: "Giron"
    label: "Enter last name"

  - id: projectsLeads
    type: map
    fields:
      - id: infrastructure
        type: input
        label: "Please enter the infrastructure lead"

  - id: projects
    type: list
    size: 5
    field:
      - type: input
        label: "Enter project value e.g. Infrastructure"
