description: Application Generator
fields:
  - id: name
    type: input
    default: "Otto"
    label: "Enter name"

  - id: lastName
    type: input
    default: "Giron"
    label: "Enter last name"

  - id: projectsLeads
    type: map
    label: "Enter project leads"
    fields:
      - id: infrastructure
        type: input
        label: "Please enter the infrastructure lead"

  - id: projects
    type: list
    label: "Enter the list of projects"
    size: 5
    field:
      - type: input
        label: "Enter project value e.g. Infrastructure"
