description: Application Generator
fields:
  - id: name
    type: input
    default: Otto
    label: Enter name

  - id: lastName
    type: input
    default: Giron
    label: Enter last name

  - id: projectManagers
    type: map
    label: Enter project managers
    fields:
      - id: infrastructure
        type: input
        label: Infrastructure

      - id: platform
        type: input
        label: Platform

      - id: tooling
        type: input
        label: Infrastructure
        default: Javier Alvarez

  - id: projects
    type: list
    label: Enter projects list
    size: 3
    valueField:
      type: input
      label: Project Name

  - id: envVars
    type: dmap
    label: Enter environment variables
    valueField :
      type: input
      label: Variable Name
    keyField:
      type: input
      label: Value

  - id: teams
    type: dlist
    label: Enter teams list
    size: 3
    valueField:
      type: input
      label: Team name
