description: Application Generator
fields:
  - id: name
    type: input
    default: Otto
    label: Enter name

  - id: lastName
    type: input
    default: Giron
    label: Enter last name

  - id: projectManagers
    type: map
    label: Enter project managers
    fields:
      - id: infrastructure
        type: input
        label: Enter Infrastructure manager name

      - id: platform
        type: input
        label: Enter Platform manager name

      - id: tooling
        type: input
        label: Enter Inf Tooling manager name
        default: Javier Alvarez

  - id: projects
    type: list
    label: Enter projects list
    size: 3
    value:
      type: input
      label: Project Name

  - id: envVars
    type: dmap
    label: Enter environment variables
    key:
      type: input
      label: Value
    value :
      type: input
      label: Variable Name


  - id: teams
    type: dlist
    label: Enter team list
    value:
      type: input
      label: Team name
